"""change_education_dates_to_year_only

Revision ID: f7fabaad017b
Revises: 3ddd7b759953
Create Date: 2025-09-20 15:01:02.936594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7fabaad017b'
down_revision: Union[str, Sequence[str], None] = '3ddd7b759953'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_embeddings_employee_id'), table_name='employee_embeddings')
    op.drop_index(op.f('ix_employees_department'), table_name='employees')
    op.drop_index(op.f('ix_employees_experience_years'), table_name='employees')
    op.drop_index(op.f('ix_employees_position'), table_name='employees')
    
    # Изменяем поля образования с периодов на годы
    op.alter_column('educations', 'start_period', new_column_name='start_year')
    op.alter_column('educations', 'end_period', new_column_name='end_year')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_employees_position'), 'employees', ['position'], unique=False)
    op.create_index(op.f('ix_employees_experience_years'), 'employees', ['experience_years'], unique=False)
    op.create_index(op.f('ix_employees_department'), 'employees', ['department'], unique=False)
    op.create_index(op.f('ix_employee_embeddings_employee_id'), 'employee_embeddings', ['employee_id'], unique=False)
    
    # Возвращаем поля образования обратно к периодам
    op.alter_column('educations', 'start_year', new_column_name='start_period')
    op.alter_column('educations', 'end_year', new_column_name='end_period')
    # ### end Alembic commands ###
