"""change_embedding_to_json_type

Revision ID: ff14d24443c2
Revises: c71d9b715001
Create Date: 2025-09-20 14:06:00.145786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff14d24443c2'
down_revision: Union[str, Sequence[str], None] = 'c71d9b715001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE employee_embeddings ALTER COLUMN embedding TYPE JSON USING embedding::json")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE employee_embeddings ALTER COLUMN embedding TYPE TEXT USING embedding::text")
    # ### end Alembic commands ###
